### ISSUE TITLE
Not seeming to gather any, Logs showing this. 

### ISSUE THREAD

**Issue by brianoflondon** [plaintextpackets/netprobe_lite#11]
I'm running from docker compose, only edits were to put my own local ISP DNS in the `.env` though I note that removing that change makes no difference to this.

```
netprobe-presentation  | Traceback (most recent call last):
netprobe-presentation  |   File "/usr/lib/python3.12/wsgiref/handlers.py", line 137, in run
netprobe-presentation  |     self.result = application(self.environ, self.start_response)
netprobe-presentation  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/exposition.py", line 128, in prometheus_app
netprobe-presentation  |     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
netprobe-presentation  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/exposition.py", line 104, in _bake_output
netprobe-presentation  |     output = encoder(registry)
netprobe-presentation  |              ^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
netprobe-presentation  |     for metric in registry.collect():
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/registry.py", line 97, in collect
netprobe-presentation  |     yield from collector.collect()
netprobe-presentation  |   File "/netprobe_lite/presentation.py", line 101, in collect
netprobe-presentation  |     if my_dns_latency / threshold_dns_latency >= 1:
netprobe-presentation  |        ^^^^^^^^^^^^^^
netprobe-presentation  | UnboundLocalError: cannot access local variable 'my_dns_latency' where it is not associated with a value
netprobe-presentation  | Traceback (most recent call last):
netprobe-presentation  |   File "/usr/lib/python3.12/wsgiref/handlers.py", line 137, in run
netprobe-presentation  |     self.result = application(self.environ, self.start_response)
netprobe-presentation  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/exposition.py", line 128, in prometheus_app
netprobe-presentation  |     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
netprobe-presentation  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/exposition.py", line 104, in _bake_output
netprobe-presentation  |     output = encoder(registry)
netprobe-presentation  |              ^^^^^^^^^^^^^^^^^
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
netprobe-presentation  |     for metric in registry.collect():
netprobe-presentation  |   File "/usr/local/lib/python3.12/dist-packages/prometheus_client/registry.py", line 97, in collect
netprobe-presentation  |     yield from collector.collect()
netprobe-presentation  |   File "/netprobe_lite/presentation.py", line 101, in collect
netprobe-presentation  |     if my_dns_latency / threshold_dns_latency >= 1:
netprobe-presentation  |        ^^^^^^^^^^^^^^
netprobe-presentation  | UnboundLocalError: cannot access local variable 'my_dns_latency' where it is not associated with a value
```

**Comment by joeypel** [comment]
I would reset your .env file back to an unmodified version and ONLY change the DNS IP address and not the name.

```
DNS_NAMESERVER_4="My_DNS_Server"
DNS_NAMESERVER_4_IP="10.0.0.200" # Replace this IP with the DNS server you use at home
```
---
Otherwise if you wanted to change both lines like I did you can do the following:
```
DNS_NAMESERVER_4="PiHole"
DNS_NAMESERVER_4_IP="10.0.0.200" # Replace this IP with the DNS server you use at home
```
and make the accompanying change in presentation.py
```
 if item['nameserver'] == 'My_DNS_Server':
     my_dns_latency = float(item['latency']) # Grab the current DNS latency of the probe's DNS resolver
   
```
to
```
if item['nameserver'] == 'PiHole':
    my_dns_latency = float(item['latency']) # Grab the current DNS latency of the probe's DNS resolver 
```

**Comment by brianoflondon** [comment]
Ahhhh OK that makes sense. You could probably replace the right side of the comparison with the ENV but no worries!

Working now. I should have looked at the code and figured it out myself.
